Repository bcgov/jag-ecrc, pull requests merged in 2020-03, with the labels that each got.

#93 Authentication Helper
  src/.gitignore
  src/ecrc-api/pom.xml
  src/ecrc-frontend/README.md
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/index.js
  src/ecrc-frontend/src/modules/AuthenticationHelper.js
Labels: enhancement

#98 BCSC Integration FE
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.js
Labels: enhancement

#100 add fix to payment calls
  src/ecrc-frontend/src/components/page/success/Success.js
Labels: bug, enhancement

#118 BCSC Redirect page - ticket 367
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/bcscRedirect/__snapshots__/BcscRedirect.test.js.snap
  src/ecrc-frontend/src/storyshots.test.js
Labels: enhancement

#119 Consent page changes - ticket 368
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/declaration/Declaration.js
  src/ecrc-frontend/src/components/base/declaration/Declaration.stories.js
  src/ecrc-frontend/src/components/base/declaration/Declaration.test.js
  src/ecrc-frontend/src/components/base/declaration/__snapshots__/Declaration.test.js.snap
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
Labels: enhancement

#120 add message to notify user to scroll in Terms of use page
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/base/termsOfUse/__snapshots__/TermsOfUse.test.js.snap
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
Labels: enhancement

#131 Secure frontend page routes!
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.stories.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/Consent.stories.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.test.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.test.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.test.js
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/Success.test.js
  src/ecrc-frontend/src/components/page/tou/TOU.js
  src/ecrc-frontend/src/components/page/tou/TOU.test.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.stories.js
  src/ecrc-frontend/src/index.js
  src/ecrc-frontend/src/modules/AuthenticationHelper.js
  src/ecrc-frontend/src/setupTests.js
  src/ecrc-frontend/src/storyshots.test.js
Labels: enhancement

#135 Fix error with route protection post bcsc
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.js
Labels: bug

#136 Add GUID to all backend calls and also fix issues with route redirects
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/consent/Consent.stories.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.test.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.test.js
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/Success.test.js
  src/ecrc-frontend/src/components/page/tou/TOU.test.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.js
  src/ecrc-frontend/src/modules/AuthenticationHelper.js
Labels: bug, enhancement

#138 /criminalrecordcheck route
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.test.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.test.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.test.js
  src/ecrc-frontend/src/components/page/tou/TOU.js
  src/ecrc-frontend/src/components/page/tou/TOU.test.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.js
Labels: enhancement

#143 remove image folder
  images/u589.png
Labels: enhancement

#144 Fix initial handshake
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/modules/AuthenticationHelper.js
Labels: bug

#146 fix issues with stories
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/composite/simpleForm/SimpleForm.stories.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.stories.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.stories.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/Consent.stories.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.stories.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.stories.js
  src/ecrc-frontend/src/components/page/success/Success.stories.js
  src/ecrc-frontend/src/components/page/tou/TOU.stories.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.stories.js
Labels: bug, enhancement

#145 Get jest working instead of react-scripts test
  src/ecrc-frontend/.babelrc
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/AssetsTransformer.js
  src/ecrc-frontend/src/setupTests.js
Labels: enhancement

#148 fix storyshots
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
Labels: bug

#157 Org Validation Page Layout Changes
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.js
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.test.js
  src/ecrc-frontend/src/components/base/orgValidationText/__snapshots__/OrgValidationText.test.js.snap
  src/ecrc-frontend/src/components/base/textInput/TextInput.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.stories.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.stories.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.stories.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.test.js
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.stories.js
  src/ecrc-frontend/src/components/page/tou/TOU.stories.js
Labels: enhancement

#158 Org validation layout -> minor updates and fixes
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.js
  src/ecrc-frontend/src/components/base/orgValidationText/__snapshots__/OrgValidationText.test.js.snap
  src/ecrc-frontend/src/components/page/consent/Consent.stories.js
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
Labels: enhancement

#160 Move consent page
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/Consent.stories.js
  src/ecrc-frontend/src/components/page/consent/Consent.test.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.stories.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.test.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.js
Labels: enhancement

#162 org verification layout & sidecards & bcscredirect
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.css
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/composite/sideCards/__snapshots__/SideCards.test.js.snap
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/bcscRedirect/__snapshots__/BcscRedirect.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
Labels: enhancement

#172 Testing homepage to fix proxy
  src/ecrc-frontend/package.json
Labels: help wanted

#170 Terms of use layout changes
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.css
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.stories.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.test.js
  src/ecrc-frontend/src/components/base/termsOfUse/__snapshots__/TermsOfUse.test.js.snap
  src/ecrc-frontend/src/components/page/tou/TOU.js
  src/ecrc-frontend/src/components/page/tou/TOU.test.js
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
Labels: enhancement

#174 Move button on org validation page
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.js
  src/ecrc-frontend/src/components/base/orgValidationText/__snapshots__/OrgValidationText.test.js.snap
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
Labels: enhancement

#175 change sidecards spacing to wide
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
Labels: enhancement

#177 fix vulnerability
  src/eCRC_qaautomation/package-lock.json
Labels: bug

#179 Layout changes (cont.)
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/button/Button.css
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/base/termsOfUse/__snapshots__/TermsOfUse.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.test.js
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
Labels: enhancement

#181 Remove user confirmation
  src/eCRC_qaautomation/.env.template
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.stories.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.stories.js
  src/ecrc-frontend/src/components/page/consent/Consent.stories.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.stories.js
  src/ecrc-frontend/src/components/page/success/Success.stories.js
  src/ecrc-frontend/src/components/page/tou/TOU.js
  src/ecrc-frontend/src/components/page/tou/TOU.stories.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.css
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.stories.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.test.js
  src/ecrc-frontend/src/components/page/userConfirmation/__snapshots__/UserConfirmation.test.js.snap
Labels: enhancement

#185 Volunteer flow fix
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/success/Success.js
Labels: bug, enhancement

#186 Layout changes (cont.)
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.css
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
Labels: enhancement

#190 Terms of use bug fix, redirect and ui on transition page
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/base/termsOfUse/__snapshots__/TermsOfUse.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/composite/sideCards/__snapshots__/SideCards.test.js.snap
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
  src/ecrc-frontend/src/components/page/tou/TOU.js
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
  src/ecrc-frontend/src/components/page/transition/Transition.css
  src/ecrc-frontend/src/components/page/transition/Transition.js
  src/ecrc-frontend/src/components/page/transition/__snapshots__/Transition.test.js.snap
Labels: enhancement

#191 Use protected for getProvinceList call
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
Labels: bug

#192 add fix for getprovince list
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
Labels: bug

#196 fix storyshots in master
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
Labels: bug

#197 Stylistic changes on success page
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/__snapshots__/Success.test.js.snap
Labels: enhancement

#200 Ensure access code not empty, links update
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/menuItem/MenuItem.js
  src/ecrc-frontend/src/components/base/menuItem/__snapshots__/MenuItem.test.js.snap
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.js
  src/ecrc-frontend/src/components/base/orgValidationText/__snapshots__/OrgValidationText.test.js.snap
  src/ecrc-frontend/src/components/base/sideCard/SideCard.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/base/termsOfUse/__snapshots__/TermsOfUse.test.js.snap
  src/ecrc-frontend/src/components/base/textInput/TextInput.js
  src/ecrc-frontend/src/components/base/textInput/__snapshots__/TextInput.test.js.snap
  src/ecrc-frontend/src/components/composite/fullName/__snapshots__/FullName.test.js.snap
  src/ecrc-frontend/src/components/composite/menu/__snapshots__/Menu.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/composite/sideCards/__snapshots__/SideCards.test.js.snap
  src/ecrc-frontend/src/components/composite/simpleForm/__snapshots__/SimpleForm.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/bcscRedirect/__snapshots__/BcscRedirect.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
  src/ecrc-frontend/src/components/page/transition/Transition.js
  src/ecrc-frontend/src/components/page/transition/__snapshots__/Transition.test.js.snap
Labels: enhancement

#204 termsofuse bug fix
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/header/Header.css
  src/ecrc-frontend/src/components/base/header/Header.js
  src/ecrc-frontend/src/components/base/header/Header.stories.js
  src/ecrc-frontend/src/components/base/header/Header.test.js
  src/ecrc-frontend/src/components/base/header/__snapshots__/Header.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/bcscRedirect/__snapshots__/BcscRedirect.test.js.snap
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/error/__snapshots__/Error.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
  src/ecrc-frontend/src/components/page/success/__snapshots__/Success.test.js.snap
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
  src/ecrc-frontend/src/components/page/transition/Transition.stories.js
  src/ecrc-frontend/src/components/page/transition/Transition.test.js
  src/ecrc-frontend/src/components/page/transition/__snapshots__/Transition.test.js.snap
  src/ecrc-frontend/src/components/page/userConfirmation/__snapshots__/UserConfirmation.test.js.snap
Labels: bug, enhancement

#205 update sidecard caps lock and tests
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
Labels: bug

#208 Bug fixes
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/declaration/Declaration.js
  src/ecrc-frontend/src/components/base/declaration/__snapshots__/Declaration.test.js.snap
  src/ecrc-frontend/src/components/base/menuItem/MenuItem.css
  src/ecrc-frontend/src/components/base/sideCard/SideCard.css
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.css
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/composite/sideCards/__snapshots__/SideCards.test.js.snap
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.css
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/bcscRedirect/__snapshots__/BcscRedirect.test.js.snap
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
Labels: bug, enhancement

#212 Make master releasable
  src/eCRC_qaautomation/.env.template
  src/eCRC_qaautomation/automationtest/moduletests/landingpage_spec.js
  src/eCRC_qaautomation/automationtest/moduletests/termsofusepage_spec.js
  src/eCRC_qaautomation/pageobjectfactory/applicationformpage.js
  src/eCRC_qaautomation/pageobjectfactory/bcscconsentpage.js
  src/eCRC_qaautomation/pageobjectfactory/bcservicescardlandingpage.js
  src/eCRC_qaautomation/pageobjectfactory/bcservicescardloginpage.js
  src/eCRC_qaautomation/pageobjectfactory/consentpage.js
  src/eCRC_qaautomation/pageobjectfactory/landingpage.js
  src/eCRC_qaautomation/pageobjectfactory/orgverificationpage.js
  src/eCRC_qaautomation/pageobjectfactory/paymentpage.js
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/header/Header.js
  src/ecrc-frontend/src/components/base/header/__snapshots__/Header.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.stories.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.stories.js
  src/ecrc-frontend/src/components/page/bcscRedirect/__snapshots__/BcscRedirect.test.js.snap
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/Consent.stories.js
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/error/__snapshots__/Error.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.stories.js
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.stories.js
  src/ecrc-frontend/src/components/page/success/__snapshots__/Success.test.js.snap
  src/ecrc-frontend/src/components/page/tou/TOU.stories.js
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
  src/ecrc-frontend/src/components/page/transition/__snapshots__/Transition.test.js.snap
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.css
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.stories.js
  src/ecrc-frontend/src/components/page/userConfirmation/UserConfirmation.test.js
  src/ecrc-frontend/src/components/page/userConfirmation/__snapshots__/UserConfirmation.test.js.snap
Labels: enhancement

#216 Content updates
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.js
  src/ecrc-frontend/src/components/base/orgValidationText/__snapshots__/OrgValidationText.test.js.snap
  src/ecrc-frontend/src/components/base/sideCard/SideCard.stories.js
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/composite/sideCards/__snapshots__/SideCards.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/bcscRedirect/__snapshots__/BcscRedirect.test.js.snap
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
  src/ecrc-frontend/src/components/page/transition/Transition.js
  src/ecrc-frontend/src/components/page/transition/__snapshots__/Transition.test.js.snap
Labels: enhancement

#217 updates to sidecard - as per SPDBCSC 506
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.css
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/composite/sideCards/__snapshots__/SideCards.test.js.snap
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
Labels: enhancement

#222 update sidecard url
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/composite/sideCards/__snapshots__/SideCards.test.js.snap
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
Labels: bug

#223 Remove ecrc routes
  src/ecrc-frontend/src/App.js
Labels: enhancement

#226 Cant leave eCRC process
  src/ecrc-frontend/src/components/base/header/Header.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/Consent.test.js
  src/ecrc-frontend/src/components/page/tou/TOU.test.js
  src/ecrc-frontend/src/index.js
Labels: enhancement

#228 Fixes
  src/ecrc-frontend/src/components/base/header/Header.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/error/Error.js
Labels: bug, enhancement

#233 SPDBCSC 529
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/__snapshots__/Success.test.js.snap
Labels: enhancement
