Repository bcgov/jag-ecrc, pull requests merged in 2020-04, with the labels that each got.

#236 Final content updates
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/declaration/Declaration.js
  src/ecrc-frontend/src/components/base/declaration/__snapshots__/Declaration.test.js.snap
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/Consent.test.js
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
Labels: enhancement

#239 update warning message on leaving success page
  src/ecrc-frontend/src/components/base/header/Header.js
  src/ecrc-frontend/src/components/page/success/Success.js
Labels: bug, enhancement

#243 Grammarly ;)
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/bcscRedirect/__snapshots__/BcscRedirect.test.js.snap
Labels: bug

#242 SPDBCSC 523
  src/ecrc-frontend/public/images/bc-gov-logo.png
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/__snapshots__/Success.test.js.snap
Labels: enhancement

#246 Technical Debt - Jest
  src/ecrc-frontend/src/components/base/loader/Loader.test.js
  src/ecrc-frontend/src/components/base/loader/__snapshots__/Loader.test.js.snap
  src/ecrc-frontend/src/components/composite/share/Share.stories.js
  src/ecrc-frontend/src/components/composite/share/Share.test.js
  src/ecrc-frontend/src/components/composite/share/__snapshots__/Share.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.stories.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/consent/Consent.test.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.test.js
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.stories.js
Labels: bug, enhancement

#252 Fix all storybook stories
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/footer/Footer.stories.js
  src/ecrc-frontend/src/components/base/header/Header.stories.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.stories.js
  src/ecrc-frontend/src/components/page/success/Success.stories.js
Labels: bug, enhancement

#270 Success page receipt and fixes to error
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/Success.test.js
  src/ecrc-frontend/src/components/page/success/__snapshots__/Success.test.js.snap
  src/ecrc-frontend/src/index.js
Labels: bug, enhancement

#283 Leave app and coming back error state
  src/ecrc-frontend/src/components/composite/table/Table.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.test.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/Consent.test.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.test.js
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/tou/TOU.js
  src/ecrc-frontend/src/index.js
Labels: bug, enhancement

#285 fix broken master
  src/ecrc-frontend/src/index.js
Labels: bug

#287 SPDBCSC 420
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.css
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/Success.test.js
  src/ecrc-frontend/src/components/page/success/__snapshots__/Success.test.js.snap
Labels: enhancement

#290 SPDBCSC 554
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/__snapshots__/Success.test.js.snap
Labels: bug, enhancement

#293 Improve test coverage (Part 1)
  src/ecrc-frontend/src/components/base/header/Header.js
  src/ecrc-frontend/src/components/base/header/Header.test.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.test.js
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.test.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/error/Error.test.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.test.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.test.js
  src/ecrc-frontend/src/components/page/success/Success.test.js
  src/ecrc-frontend/src/components/page/tou/TOU.test.js
  src/ecrc-frontend/src/components/page/transition/Transition.test.js
Labels: enhancement

#295 Sonar bugs and App Form Route protection
  src/ecrc-frontend/src/components/base/textInput/TextInput.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.stories.js
Labels: bug

#302 Sonar fixes
  src/ecrc-api/src/main/java/ca/bc/gov/open/ecrc/controller/CreateApplicantController.java
  src/ecrc-api/src/main/java/ca/bc/gov/open/ecrc/model/RequestNewCRCService.java
  src/ecrc-api/src/main/java/ca/bc/gov/open/ecrc/model/RequestUpdateServiceFinancialTxn.java
  src/ecrc-api/src/main/java/ca/bc/gov/open/ecrc/service/EcrcServicesImpl.java
  src/ecrc-api/src/test/java/ca/bc/gov/open/ecrc/model/RequestNewCRCServiceTest.java
  src/ecrc-api/src/test/java/ca/bc/gov/open/ecrc/model/RequestUpdateServiceFinancialTxnTest.java
  src/ecrc-api/src/test/java/ca/bc/gov/open/ecrc/service/EcrcServicesImplUpdateServiceFinancialTxnTest.java
Labels: breaking change, do not merge

#301 Refactor: Remove underscore for API calls
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/success/Success.js
Labels: do not merge

#303 fix json parse issue, defensively
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/success/Success.js
Labels: bug

#305 Cleanup sonar test coverage and code duplications
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/header/Header.test.js
  src/ecrc-frontend/src/components/base/sideCard/SideCard.js
  src/ecrc-frontend/src/components/base/sideCard/SideCard.test.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.test.js
  src/ecrc-frontend/src/components/base/termsOfUse/__snapshots__/TermsOfUse.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.stories.js
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.test.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.test.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.test.js
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/tou/TOU.test.js
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
  src/ecrc-frontend/src/modules/AuthenticationHelper.js
  src/ecrc-frontend/src/modules/AuthenticationHelper.test.js
Labels: enhancement

#313 Sonar improvements (cont.) -> information review
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.test.js
Labels: enhancement

#316 More test improvements (FE)
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/Success.test.js
Labels: enhancement

#318 SPDBCSC 569
  src/ecrc-frontend/src/components/page/transition/Transition.js
Labels: bug

#321 Consent content and tests updates (FE)
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/declaration/Declaration.js
  src/ecrc-frontend/src/components/base/declaration/__snapshots__/Declaration.test.js.snap
  src/ecrc-frontend/src/components/base/textInput/TextInput.test.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.test.js
  src/ecrc-frontend/src/components/page/applicationForm/__snapshots__/ApplicationForm.test.js.snap
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.test.js
Labels: enhancement

#324 add PUBLIC_URL, it is causing 404
  src/ecrc-frontend/public/404.html
  src/ecrc-frontend/public/index.html
Labels: bug

#328 give broken images types
  src/ecrc-frontend/public/index.html
Labels: bug

#340 Reduce code duplication in inforeview stories
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.stories.js
Labels: enhancement

#342 SPDBCSC 569 (version 2)
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/applicationForm/ApplicationForm.js
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/tou/TOU.js
  src/ecrc-frontend/src/components/page/transition/Transition.css
  src/ecrc-frontend/src/components/page/transition/Transition.js
  src/ecrc-frontend/src/components/page/transition/Transition.test.js
  src/ecrc-frontend/src/components/page/transition/__snapshots__/Transition.test.js.snap
Labels: bug, enhancement

#343 Dockerize Frontend
  src/ecrc-frontend/.dockerignore
  src/ecrc-frontend/Dockerfile
  src/ecrc-frontend/docker-compose.yml
Labels: enhancement

#345 Docker Updates (cont.)
  src/ecrc-frontend/Dockerfile
  src/ecrc-frontend/README.md
  src/ecrc-frontend/docker-compose.yml
Labels: documentation, enhancement

#354 SPDBCSC 586
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/success/Success.css
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/__snapshots__/Success.test.js.snap
Labels: enhancement

#366 Add tests to address missing coverage sections
  src/ecrc-frontend/src/components/page/consent/Consent.test.js
Labels: enhancement

#369 Fix spacing on inforeview page
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
Labels: enhancement

#378 fix tou download link
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.test.js
Labels: documentation, enhancement

#387 add post bcsc login screenshots
  README.md
Labels: enhancement

#389 Final content changes
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/base/declaration/Declaration.js
  src/ecrc-frontend/src/components/base/declaration/__snapshots__/Declaration.test.js.snap
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.js
  src/ecrc-frontend/src/components/base/orgValidationText/__snapshots__/OrgValidationText.test.js.snap
  src/ecrc-frontend/src/components/composite/share/Share.js
  src/ecrc-frontend/src/components/composite/share/__snapshots__/Share.test.js.snap
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.js
  src/ecrc-frontend/src/components/page/informationreview/InformationReview.test.js
  src/ecrc-frontend/src/components/page/informationreview/__snapshots__/InformationReview.test.js.snap
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
  src/ecrc-frontend/src/components/page/transition/Transition.js
  src/ecrc-frontend/src/components/page/transition/__snapshots__/Transition.test.js.snap
Labels: enhancement

#393 Fix Print issue on Payment page
  src/ecrc-frontend/src/components/page/success/Success.js
  src/ecrc-frontend/src/components/page/success/Success.test.js
Labels: bug

#396 Remove and fix useful org verification page links
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
Labels: enhancement
