Repository bcgov/jag-ecrc, pull requests merged in 2020-02, with the labels that each got.

#11 Add terms of use, finish initial org validation page content/layout
  src/ecrc-frontend/.eslintrc.js
  src/ecrc-frontend/public/images/visit-criminal-record-site.PNG
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/components/base/orgvalidationtext/OrgValidationText.js
  src/ecrc-frontend/src/components/base/orgvalidationtext/OrgValidationText.test.js
  src/ecrc-frontend/src/components/base/orgvalidationtext/__snapshots__/OrgValidationText.test.js.snap
  src/ecrc-frontend/src/components/base/sideCard/SideCard.css
  src/ecrc-frontend/src/components/base/sideCard/SideCard.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.css
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.stories.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.test.js
  src/ecrc-frontend/src/components/base/termsOfUse/__snapshots__/TermsOfUse.test.js.snap
  src/ecrc-frontend/src/components/composite/simpleForm/SimpleForm.js
  src/ecrc-frontend/src/components/page/orgvalidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/orgvalidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/page.css
Labels: enhancement

#4 Minor readme update
  README.md
Labels: enhancement

#23 Rename folders to camelCase
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.css
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.js
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.stories.js
  src/ecrc-frontend/src/components/base/orgValidationText/OrgValidationText.test.js
  src/ecrc-frontend/src/components/base/orgValidationText/__snapshots__/OrgValidationText.test.js.snap
  src/ecrc-frontend/src/components/base/tableElement/TableElement.css
  src/ecrc-frontend/src/components/base/tableElement/TableElement.js
  src/ecrc-frontend/src/components/base/tableElement/TableElement.stories.js
  src/ecrc-frontend/src/components/base/tableElement/TableElement.test.js
  src/ecrc-frontend/src/components/base/tableElement/__snapshots__/TableElement.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.css
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.js
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.stories.js
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.test.js
  src/ecrc-frontend/src/components/composite/sideCards/__snapshots__/SideCards.test.js.snap
  src/ecrc-frontend/src/components/composite/table/Table.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.stories.js
  src/ecrc-frontend/src/components/page/orgValidation/OrgValidation.test.js
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.stories.js
  src/ecrc-frontend/src/components/page/orgVerification/OrgVerification.test.js
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
Labels: enhancement

#31 App.js -> fix path to file
  src/ecrc-frontend/src/App.js
Labels: bug

#32 Fix page styling
  src/ecrc-frontend/src/components/base/menuItem/MenuItem.css
  src/ecrc-frontend/src/components/composite/sideCards/SideCards.css
Labels: bug

#35 SPDBCSC-251: Add transition page
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/components/base/footer/Footer.js
  src/ecrc-frontend/src/components/base/footer/__snapshots__/Footer.test.js.snap
  src/ecrc-frontend/src/components/page/orgValidation/__snapshots__/OrgValidation.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
  src/ecrc-frontend/src/components/page/transition/Transition.css
  src/ecrc-frontend/src/components/page/transition/Transition.js
  src/ecrc-frontend/src/components/page/transition/Transition.stories.js
  src/ecrc-frontend/src/components/page/transition/Transition.test.js
  src/ecrc-frontend/src/components/page/transition/__snapshots__/Transition.test.js.snap
Labels: enhancement

#43 add proper links to transition page
  src/ecrc-frontend/src/components/page/transition/Transition.css
  src/ecrc-frontend/src/components/page/transition/Transition.js
  src/ecrc-frontend/src/components/page/transition/__snapshots__/Transition.test.js.snap
Labels: enhancement

#54 add scroll , checkbox and btn state for term of use
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/components/base/button/Button.css
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.js
  src/ecrc-frontend/src/components/base/termsOfUse/TermsOfUse.test.js
  src/ecrc-frontend/src/components/base/termsOfUse/__snapshots__/TermsOfUse.test.js.snap
  src/ecrc-frontend/src/components/page/bcscRedirect/BcscRedirect.css
  src/ecrc-frontend/src/components/page/consent/Consent.js
  src/ecrc-frontend/src/components/page/consent/Consent.stories.js
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/tou/TOU.js
  src/ecrc-frontend/src/components/page/tou/__snapshots__/TOU.test.js.snap
Labels: do not merge
