Repository bcgov/jag-ecrc, pull requests merged in 2021-12, with the labels that each got.

#426 Log4j Bug Fix
  src/ecrc-api/pom.xml
Labels: question

#427 Update pom.xml
  src/ecrc-api/pom.xml
Labels: help wanted

#432 Bug/vulnerability fixes
  src/ecrc-api/.env.template
  src/ecrc-frontend/.eslintrc.js
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/__snapshots__/storyshots.test.js.snap
  src/ecrc-frontend/src/components/composite/sideCards/__snapshots__/SideCards.test.js.snap
  src/ecrc-frontend/src/components/page/consent/__snapshots__/Consent.test.js.snap
  src/ecrc-frontend/src/components/page/orgVerification/__snapshots__/OrgVerification.test.js.snap
  src/ecrc-frontend/yarn.lock
Labels: bug, dependencies, front end

#435 Bump version
  src/ecrc-api/pom.xml
Labels: good first issue

#439 Update log4j and splunk
  src/ecrc-api/pom.xml
Labels: good first issue
